// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CopyFileContents;

internal sealed partial class Vsix {
	public const string Id = "CopyFileContents.99fe0985-b52d-44f1-8af2-863b1a8d1512";
	public const string Name = "CopyFileContents";
	public const string Description = @"Empty VSIX Project.";
	public const string Language = "en-US";
	public const string Version = "1.0";
	public const string Author = "Armindo Gomes";
	public const string Tags = "";
}
