// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CopyFileContents
{
    internal sealed partial class Vsix
    {
        public const string Id = "CopyFileContents.99fe0985-b52d-44f1-8af2-863b1a8d1512";
        public const string Name = "Copy File Contents";
        public const string Description = @"Copy File Contents is a Visual Studio extension that lets you quickly copy the contents of one or more files selected in the Solution Explorer to the clipboard";
        public const string Language = "en-US";
        public const string Version = "1.0.6";
        public const string Author = "Armindo Gomes";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
