// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CopyFileContents
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string CopyFileContentsString = "bad1b592-fd69-4e09-bf85-daed5bb1b9a1";
        public static Guid CopyFileContents = new Guid(CopyFileContentsString);

        public const string guidCopyFileContentsString = "bad1b592-fd69-4e09-bf85-daed5bb1b9a1";
        public static Guid guidCopyFileContents = new Guid(guidCopyFileContentsString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ContentClipboardGroup = 0x0001;
        public const int CopyToClipboardCommand = 0x0100;
    }
}
